[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.1"
bindgen = { version = "0.70", default-features = false, features = ["runtime"] }

[dependencies]
libc = "0.2"
