name: Perft tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  perft:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cd src/engine
          make chess
          cd ../..

      - name: Run perft tests (cargo)
        run: cargo test engine --release -- --nocapture
